import { useState, useEffect } from "react";
import Link from "next/link";
import { MainLayout } from "@/layouts";
import { Breadcrumbs, Card, Pagination, TableField } from "@/components/atoms";
import Button from "@atlaskit/button";
import {
  IconArrowRight,
  // IconClose, IconPlus
} from "@/components/icons";
// import Select from "@atlaskit/select";
// import Textfield from "@atlaskit/textfield";

const rpmData = [
  {
    project_rpm_id: 21,
    rpm: {
      id: 21,
      project_id: 20230142,
      nama_project: "Fase II testing",
      num_project: "20230142",
      status_project: "Final",
      batas_waktu: "2023-10-27T10:55:30.878+07:00",
      tim_audit: [
        {
          title: "ma",
          pn: "00071542",
          nama: "Bahrul Ulum",
          jabatan: "Auditor",
        },
        {
          title: "kta",
          pn: "1892-0472",
          nama: "Riva Annisa",
          jabatan: "Auditor",
        },
        {
          title: "ata",
          pn: "1991-0585",
          nama: "Eko Setiawan",
          jabatan: "Auditor",
        },
      ],
      pic_auditee: {
        name: "ioloili",
        pn: "3427197",
      },
      auditee_pn: ["3427197"],
      auditor_pn: [
        "1991-0585",
        "1973-0878",
        "2297-1625",
        "00071542",
        "1892-0472",
      ],
      makers_auditee: null,
      checkers_auditee: null,
      signers_auditee: null,
      makers_auditor: [
        {
          pn: "1991-0585",
          nama: "Eko Setiawan",
          jabatan: "Auditor",
          deskripsi_tugas: "fadf",
        },
      ],
      checkers_auditor: [
        {
          pn: "2297-1625",
          nama: "Ignatia Gladys R. Tondang",
          jabatan: "Auditor",
          deskripsi_tugas: "sdfaf",
        },
      ],
      signers_auditor: [
        {
          pn: "1973-0878",
          nama: "Titis Agung Pramono",
          jabatan: "Auditor",
          deskripsi_tugas: "adfafda",
        },
      ],
      num_evaluasi: 1,
      create_by: {
        pn: "1892-0472",
        nama: "Riva Annisa",
        jabatan: "Auditor",
      },
      update_by: {
        pn: "1892-0472",
        nama: "Riva Annisa",
        jabatan: "Auditor",
      },
      createdAt: "2023-07-11T11:01:13.112+07:00",
      updatedAt: "2023-07-11T11:27:25.969+07:00",
      status_rpm: "Final",
      kai: {
        nama: "Bahrul Ulum",
        pn: "00071542",
      },
      uka_kode: "aikp1",
    },
    kkpt_rpm: [
      {
        kkpt_rpm_id: 21,
        id: 21,
        kkpt_id: 33,
        nama_kkpt: "KKPT 1",
        project_rpm_id: 21,
        batas_waktu: "2023-10-31T10:55:07.161+07:00",
        rekomendasi_existing: 3,
        action_plan_existing: 3,
        rekomendasi_terisi: 3,
        action_plan_terisi: 3,
        createdAt: "2023-07-11T11:01:13.118+07:00",
        updatedAt: "2023-07-11T11:27:04.891+07:00",
        kkpt_ewp: {
          kkpt: {
            id: 33,
            exemplar_no: 1,
            is_kkpt_merge: false,
            kkpt_merge_from: null,
            kkpt_merge_to: null,
            judul_kkpt: "KKPT 1",
            is_temuan_berulang: false,
            mtd_stc_risk_type_kode: "7",
            mtd_stc_risk_type_name: "Risiko Kepatuhan",
            audit_focus_kode: "fa1",
            audit_focus_name: "Focus Audit 1",
            products_kode: ["AGF0005"],
            kondisi:
              '<p><span style="background-color:rgb(250,214,216);color:rgb(128,128,128);"><span>1892-0472</span></span></p>',
            kpi: "1892-0472",
            kriteria:
              '<p><span style="background-color:rgb(250,250,250);color:rgb(63,63,70);"><span>1991-0585</span></span></p>',
            tanggapan_manajemen: "DADADA",
            is_na: false,
            is_fraud: false,
            is_na_desc: null,
            created_at: "2023-07-11T03:45:54.573Z",
            create_by: "1991-0585",
            updated_at: "2023-07-11T03:54:51.740Z",
            update_by: "1892-0472",
            kkpa_id: 38,
            status_persetujuan: "105",
            status_persetujuan_kkpt: {
              kode: "105",
              name: "Final",
              description: null,
              create_by: "00136165",
              update_by: "00136165",
              is_active: true,
              created_at: "2021-12-20T05:04:20.382Z",
              update_at: "2021-12-20T05:04:20.382Z",
            },
            kkpt_sample_list: [
              {
                id: 61,
                value: "353501022204107",
                tipe_sample: "csv",
                objek_sample_id: "8",
                created_at: "2023-07-11T03:46:27.813Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:46:27.813Z",
                update_by: "1991-0585",
                kkpt_id: 33,
              },
              {
                id: 62,
                value: "353501022205103",
                tipe_sample: "csv",
                objek_sample_id: "8",
                created_at: "2023-07-11T03:46:27.813Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:46:27.813Z",
                update_by: "1991-0585",
                kkpt_id: 33,
              },
              {
                id: 63,
                value: "353501022206109",
                tipe_sample: "csv",
                objek_sample_id: "8",
                created_at: "2023-07-11T03:46:27.813Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:46:27.813Z",
                update_by: "1991-0585",
                kkpt_id: 33,
              },
            ],
            kkpt_control_list: [
              {
                id: 42,
                control_kode: "C1",
                created_at: "2023-07-11T03:46:34.983Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:46:34.983Z",
                update_by: "1991-0585",
                kkpt_id: 33,
              },
              {
                id: 43,
                control_kode: "C6",
                created_at: "2023-07-11T03:46:34.983Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:46:34.983Z",
                update_by: "1991-0585",
                kkpt_id: 33,
              },
            ],
            kkpt_penyebab_list: [
              {
                id: 36,
                penyebab_kode: "01.01.01",
                penyebab_name: "Training tidak sesuai dengan kebutuhan",
                desc: "1892-0472",
                pn: [],
                created_at: "2023-07-11T03:46:50.794Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:46:50.794Z",
                update_by: "1991-0585",
                kkpt_id: 33,
              },
            ],
            kkpt_impact: {
              id: 33,
              impact_kode: "SR",
              desc_impact: null,
              financial_impact_kode: "SR",
              financial_type_impact_kode: "mk0",
              total_kerugian: null,
              gross: "0",
              list_kerugian: null,
              nonfinancial_impact_kode: "SR",
              list_nonfinancial: null,
              created_at: "2023-07-11T03:45:54.578Z",
              create_by: "1991-0585",
              updated_at: "2023-07-11T03:45:54.578Z",
              update_by: "1991-0585",
              kkpt_id: 33,
            },
            kkpt_likelihood: {
              id: 33,
              jumlah_populasi: 6,
              jumlah_sample: 3,
              jumlah_sample_bermasalah: 3,
              likelihood_kode: "SR",
              created_at: "2023-07-11T03:45:54.585Z",
              create_by: "1991-0585",
              updated_at: "2023-07-11T03:45:54.585Z",
              update_by: "1991-0585",
              kkpt_id: 33,
            },
            kkpt_kategori: {
              id: 33,
              kategori_temuan_kode: "2",
              adj_impact_kode: null,
              adj_likelihood_kode: null,
              adj_kategori_temuan_kode: null,
              adj_alasan: null,
              adj_by: null,
              adj_at: null,
              created_at: "2023-07-11T03:45:54.585Z",
              create_by: "1991-0585",
              updated_at: "2023-07-11T03:46:27.827Z",
              update_by: "1991-0585",
              kkpt_id: 33,
            },
            kkpt_rekomendasi_list: [
              {
                id: 44,
                tipe_rekomendasi_kode: "3",
                tipe_rekomendasi_name: "tindakan",
                desc: "1892-0472",
                ref_uker_tujuan_branch_kode: 5,
                ref_uker_tujuan_branch_name: "DIVISI TEKNOLOGI INFORMASI",
                ref_uker_tujuan_orgeh: 5,
                ref_uker_tujuan_orgeh_name: "DIVISI TEKNOLOGI INFORMASI",
                created_at: "2023-07-11T03:48:04.035Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:48:04.035Z",
                update_by: "1991-0585",
                kkpt_id: 33,
                action_plans: [
                  {
                    id: 26,
                    desc: "SFSFSF",
                    rekomendasi_id: 44,
                    ref_auditee_branch_kode: 5,
                    ref_auditee_orgeh: 5,
                    batas_waktu: "2023-07-21T03:55:18.077Z",
                    pic: "1991-0585",
                  },
                ],
              },
              {
                id: 42,
                tipe_rekomendasi_kode: "1",
                tipe_rekomendasi_name: "preventive",
                desc: "1892-0472",
                ref_uker_tujuan_branch_kode: 5,
                ref_uker_tujuan_branch_name: "DIVISI TEKNOLOGI INFORMASI",
                ref_uker_tujuan_orgeh: 5,
                ref_uker_tujuan_orgeh_name: "DIVISI TEKNOLOGI INFORMASI",
                created_at: "2023-07-11T03:47:38.794Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:47:38.794Z",
                update_by: "1991-0585",
                kkpt_id: 33,
                action_plans: [
                  {
                    id: 29,
                    desc: "FFSDFS",
                    rekomendasi_id: 42,
                    ref_auditee_branch_kode: 5,
                    ref_auditee_orgeh: 5,
                    batas_waktu: "2023-10-31T03:55:07.161Z",
                    pic: "1991-0585",
                  },
                ],
              },
              {
                id: 43,
                tipe_rekomendasi_kode: "2",
                tipe_rekomendasi_name: "corrective",
                desc: "GGGG",
                ref_uker_tujuan_branch_kode: 5,
                ref_uker_tujuan_branch_name: "DIVISI TEKNOLOGI INFORMASI",
                ref_uker_tujuan_orgeh: 5,
                ref_uker_tujuan_orgeh_name: "DIVISI TEKNOLOGI INFORMASI",
                created_at: "2023-07-11T03:47:52.780Z",
                create_by: "1991-0585",
                updated_at: "2023-07-11T03:47:52.780Z",
                update_by: "1991-0585",
                kkpt_id: 33,
                action_plans: [
                  {
                    id: 30,
                    desc: "2222",
                    rekomendasi_id: 43,
                    ref_auditee_branch_kode: 5,
                    ref_auditee_orgeh: 5,
                    batas_waktu: "2023-10-27T03:55:30.878Z",
                    pic: "1892-0472",
                  },
                ],
              },
            ],
          },
          mapa_uker_mcr: {
            ref_mcr_kode: "1.1.PDP.PDP1",
            ref_risk_issue_kode: "PDP1",
            ref_risk_issue_name:
              "RKA uker tidak sesuai dengan kondisi bisnis dan atau potensi wilayah",
          },
          mapa_uker: {
            ref_auditee_branch_kode: 5,
            ref_auditee_branch_name: "DIVISI TEKNOLOGI INFORMASI",
            ref_auditee_orgeh_kode: 5,
            ref_auditee_orgeh_name: "DIVISI TEKNOLOGI INFORMASI",
            tipe_uker: null,
          },
          ewp: {
            audit_year: 2023,
            audit_type_kode: "SA",
            audit_type_name: "Spesial Audit",
          },
          sub_major_proses: {
            kode: "PDP",
            nama: "Penyusunan & Distribusi Perencanaan Strategis",
            mtd_major_proses_kode: "1.1",
            is_active: true,
            mtd_major_proses: {
              kode: "1.1",
              nama: "Perencanaan Strategis",
              mtd_mega_proses_kode: "1",
              is_active: true,
            },
          },
        },
        evaluasi_ke: 1,
        log_persetujuan_kkpt: [
          {
            id: 19,
            kkpt_id: 21,
            nama_kkpt: "Test 20",
            project_rpm_id: 19,
            batas_waktu: "2023-03-20T14:05:58.529+07:00",
            rekomendasi_existing: 1,
            action_plan_existing: 1,
            rekomendasi_terisi: 1,
            action_plan_terisi: 1,
            createdAt: "2023-03-20T14:06:30.904+07:00",
            updatedAt: "2023-03-20T14:08:51.55+07:00",
            kkpt_ewp: {
              kkpt: {
                id: 21,
                exemplar_no: 1,
                is_kkpt_merge: false,
                kkpt_merge_from: null,
                kkpt_merge_to: null,
                judul_kkpt: "Test 20",
                is_temuan_berulang: false,
                mtd_stc_risk_type_kode: "1",
                mtd_stc_risk_type_name: "Resiko Umum",
                audit_focus_kode: "fa2",
                audit_focus_name: "Focus Audit 2",
                products_kode: ["LOG0056"],
                kondisi:
                  "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
                kpi: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                kriteria:
                  "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
                tanggapan_manajemen: null,
                is_na: false,
                is_fraud: false,
                is_na_desc: null,
                created_at: "2023-03-20T04:51:18.344Z",
                create_by: "2297-1931",
                updated_at: "2023-03-20T04:54:26.532Z",
                update_by: "1991-0585",
                kkpa_id: 25,
                status_persetujuan: "105",
                status_persetujuan_kkpt: {
                  kode: "105",
                  name: "Final",
                  description: null,
                  create_by: "00136165",
                  update_by: "00136165",
                  is_active: true,
                  created_at: "2021-12-20T05:04:20.382Z",
                  update_at: "2021-12-20T05:04:20.382Z",
                },
                kkpt_sample_list: [
                  {
                    id: 34,
                    value: "PAT.pdf",
                    tipe_sample: "file",
                    objek_sample_id: "32",
                    created_at: "2023-03-20T04:52:01.635Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T04:52:01.635Z",
                    update_by: "2297-1931",
                    kkpt_id: 21,
                  },
                ],
                kkpt_control_list: [
                  {
                    id: 22,
                    control_kode: "C1",
                    created_at: "2023-03-20T04:52:20.637Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T04:52:20.637Z",
                    update_by: "2297-1931",
                    kkpt_id: 21,
                  },
                ],
                kkpt_penyebab_list: [
                  {
                    id: 23,
                    penyebab_kode: "04.03.02",
                    penyebab_name: "Penyebab kebakaran lainnya",
                    desc: "Test 20",
                    pn: [
                      {
                        key: 0,
                        pn: {
                          pernr: "00071542",
                          sname: "MAMAT",
                        },
                        nama: "MAMAT",
                        jabatan: "KTA",
                        tempat: "Jakarta",
                        tglLahir: "1998-05-11",
                        jenisKelamin: "L",
                        jobGrade: "1",
                        personGrade: "1",
                        mke: "Test",
                        mkj: "Test",
                        statusPerkawinan: "Lajang",
                      },
                    ],
                    created_at: "2023-03-20T04:52:59.129Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T04:52:59.129Z",
                    update_by: "2297-1931",
                    kkpt_id: 21,
                  },
                ],
                kkpt_impact: {
                  id: 21,
                  impact_kode: "SR",
                  desc_impact: "Test 20",
                  financial_impact_kode: "SR",
                  financial_type_impact_kode: "mk0",
                  total_kerugian: "384242",
                  gross: "242242",
                  list_kerugian: [
                    {
                      key: 1,
                      jumlah_kerugian: 384242,
                      jenis_kerugian: "Potensial Loss",
                      keterangan: "Loss",
                    },
                  ],
                  nonfinancial_impact_kode: "SR",
                  list_nonfinancial: [
                    {
                      nonfinancial_type_impact_kode: "cd1",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd2",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd3",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd4",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd5",
                      mtd_stc_impact_kode: "SR",
                    },
                  ],
                  created_at: "2023-03-20T04:51:18.350Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-20T04:53:22.793Z",
                  update_by: "2297-1931",
                  kkpt_id: 21,
                },
                kkpt_likelihood: {
                  id: 21,
                  jumlah_populasi: 2,
                  jumlah_sample: 1,
                  jumlah_sample_bermasalah: 1,
                  likelihood_kode: "SR",
                  created_at: "2023-03-20T04:51:18.357Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-20T04:51:18.357Z",
                  update_by: "2297-1931",
                  kkpt_id: 21,
                },
                kkpt_kategori: {
                  id: 21,
                  kategori_temuan_kode: "2",
                  adj_impact_kode: "SR",
                  adj_likelihood_kode: "SR",
                  adj_kategori_temuan_kode: "2",
                  adj_alasan: "Test 20",
                  adj_by: "2297-1931",
                  adj_at: "2023-03-20T04:53:32.697Z",
                  created_at: "2023-03-20T04:51:18.358Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-20T04:53:32.697Z",
                  update_by: "2297-1931",
                  kkpt_id: 21,
                },
                kkpt_rekomendasi_list: [
                  {
                    id: 22,
                    tipe_rekomendasi_kode: "3",
                    tipe_rekomendasi_name: "tindakan",
                    desc: "Test 20",
                    ref_uker_tujuan_branch_kode: 31,
                    ref_uker_tujuan_branch_name: "KP BANJARMASIN",
                    ref_uker_tujuan_orgeh: 31,
                    ref_uker_tujuan_orgeh_name: "KP BANJARMASIN",
                    created_at: "2023-03-20T04:53:50.332Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T04:53:50.332Z",
                    update_by: "2297-1931",
                    kkpt_id: 21,
                    action_plans: [
                      {
                        id: 23,
                        desc: "Test 20",
                        rekomendasi_id: 22,
                        ref_auditee_branch_kode: 20,
                        ref_auditee_orgeh: 20,
                        batas_waktu: "2023-03-20T07:05:58.529Z",
                        pic: "2297-1931",
                      },
                    ],
                  },
                ],
              },
              mapa_uker_mcr: {
                ref_mcr_kode: "1.1.PPP.PPP1",
                ref_risk_issue_kode: "PPP1",
                ref_risk_issue_name: "Control Masalah",
              },
              mapa_uker: {
                ref_auditee_branch_kode: 31,
                ref_auditee_branch_name: "KP BANJARMASIN",
                ref_auditee_orgeh_kode: 31,
                ref_auditee_orgeh_name: "KP BANJARMASIN",
                tipe_uker: "kc",
              },
              ewp: {
                audit_year: 2023,
                audit_type_kode: "TMT",
                audit_type_name: "Tematik",
              },
              sub_major_proses: {
                kode: "PPP",
                nama: "Pemeriksaan",
                mtd_major_proses_kode: "1.1",
                is_active: true,
                mtd_major_proses: {
                  kode: "1.1",
                  nama: "Pengujian",
                  mtd_mega_proses_kode: "1",
                  is_active: true,
                },
              },
            },
            evaluasi_ke: 1,
          },
        ],
      },
    ],
    action_plan_rpm: [
      {
        rpm_action_plan_id: 21,
        id: 21,
        project_rpm_id: 21,
        kkpt_id: 33,
        rekomendasi_kkpt: {
          prev_id: 44,
          id: 21,
          nama: "tindakan",
          description: "1892-0472",
          ref_uker_tujuan_branch_kode: 5,
          ref_uker_tujuan_branch_name: "DIVISI TEKNOLOGI INFORMASI",
          ref_uker_tujuan_orgeh: 5,
          ref_uker_tujuan_orgeh_name: "DIVISI TEKNOLOGI INFORMASI",
        },
        action_plan_kkpt: {
          prev_id: 26,
          id: 21,
          name: "SFSFSF",
          description: "SFSFSF",
        },
        batas_waktu: "2023-07-21T10:55:18.077+07:00",
        hasil_evaluasi: "Memadai",
        lampiran: [
          {
            key: "0.10436226600293441",
            attachment:
              "http://172.18.241.228:41111/cdn?id=5533141ff82a2a010a5c5abae9c81fb2.pdf@Berita Acara_Nego.pdf@RPM",
            deskripsi: "sdfsfsfs",
          },
        ],
        status_kode: "11",
        persetujuan_kode: "111",
        is_active: true,
        signed_by: ["1973-0878"],
        create_by: null,
        update_by: null,
        createdAt: "2023-07-11T11:01:13.121+07:00",
        updatedAt: "2023-07-11T11:26:56.164+07:00",
        auditee_checked_by: null,
        auditor_checked_by: "2297-1625",
        evaluasi_ke: null,
        is_late: null,
        log_persetujuan_action_plan: [
          {
            id: 61,
            from: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            to: {},
            action_plan_id: 21,
            status: "Auditor",
            role: "Maker",
            note: null,
            create_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            update_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:21:59.968+07:00",
            updatedAt: "2023-07-11T11:21:59.968+07:00",
          },
          {
            id: 64,
            from: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            to: {},
            action_plan_id: 21,
            status: "Auditor",
            role: "Checker",
            note: "afsf",
            create_by: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            update_by: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:23:34.072+07:00",
            updatedAt: "2023-07-11T11:23:34.072+07:00",
          },
          {
            id: 67,
            from: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            to: {},
            action_plan_id: 21,
            status: "Auditor",
            role: "Signer",
            note: "dfsdf",
            create_by: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            update_by: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:26:56.169+07:00",
            updatedAt: "2023-07-11T11:26:56.169+07:00",
          },
        ],
      },
      {
        rpm_action_plan_id: 22,
        id: 22,
        project_rpm_id: 21,
        kkpt_id: 33,
        rekomendasi_kkpt: {
          prev_id: 42,
          id: 22,
          nama: "preventive",
          description: "1892-0472",
          ref_uker_tujuan_branch_kode: 5,
          ref_uker_tujuan_branch_name: "DIVISI TEKNOLOGI INFORMASI",
          ref_uker_tujuan_orgeh: 5,
          ref_uker_tujuan_orgeh_name: "DIVISI TEKNOLOGI INFORMASI",
        },
        action_plan_kkpt: {
          prev_id: 29,
          id: 22,
          name: "FFSDFS",
          description: "FFSDFS",
        },
        batas_waktu: "2023-10-31T10:55:07.161+07:00",
        hasil_evaluasi: "Memadai",
        lampiran: [
          {
            key: "0.6249126122783697",
            attachment:
              "http://172.18.241.228:41111/cdn?id=ababef42d6fa5355c9326a4652e3d936.pdf@Attandance_Negosiasi.pdf@RPM",
            deskripsi: "aafafa",
          },
        ],
        status_kode: "11",
        persetujuan_kode: "111",
        is_active: true,
        signed_by: ["1973-0878"],
        create_by: null,
        update_by: null,
        createdAt: "2023-07-11T11:01:13.121+07:00",
        updatedAt: "2023-07-11T11:27:00.415+07:00",
        auditee_checked_by: null,
        auditor_checked_by: "2297-1625",
        evaluasi_ke: null,
        is_late: null,
        log_persetujuan_action_plan: [
          {
            id: 62,
            from: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            to: {},
            action_plan_id: 22,
            status: "Auditor",
            role: "Maker",
            note: null,
            create_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            update_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:22:06.298+07:00",
            updatedAt: "2023-07-11T11:22:06.298+07:00",
          },
          {
            id: 65,
            from: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            to: {},
            action_plan_id: 22,
            status: "Auditor",
            role: "Checker",
            note: "dfsfs",
            create_by: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            update_by: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:23:42.444+07:00",
            updatedAt: "2023-07-11T11:23:42.444+07:00",
          },
          {
            id: 68,
            from: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            to: {},
            action_plan_id: 22,
            status: "Auditor",
            role: "Signer",
            note: "sfs",
            create_by: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            update_by: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:27:00.42+07:00",
            updatedAt: "2023-07-11T11:27:00.42+07:00",
          },
        ],
      },
      {
        rpm_action_plan_id: 23,
        id: 23,
        project_rpm_id: 21,
        kkpt_id: 33,
        rekomendasi_kkpt: {
          prev_id: 43,
          id: 23,
          nama: "corrective",
          description: "GGGG",
          ref_uker_tujuan_branch_kode: 5,
          ref_uker_tujuan_branch_name: "DIVISI TEKNOLOGI INFORMASI",
          ref_uker_tujuan_orgeh: 5,
          ref_uker_tujuan_orgeh_name: "DIVISI TEKNOLOGI INFORMASI",
        },
        action_plan_kkpt: {
          prev_id: 30,
          id: 23,
          name: "2222",
          description: "2222",
        },
        batas_waktu: "2023-10-27T10:55:30.878+07:00",
        hasil_evaluasi: "Memadai",
        lampiran: [
          {
            key: "0.7600714047768757",
            attachment:
              "http://172.18.241.228:41111/cdn?id=baa364dee72abd172a2ef26b9d2288db.pdf@Attandance - Exit.pdf@RPM",
            deskripsi: "adadad",
          },
        ],
        status_kode: "11",
        persetujuan_kode: "111",
        is_active: true,
        signed_by: ["1973-0878"],
        create_by: null,
        update_by: null,
        createdAt: "2023-07-11T11:01:13.121+07:00",
        updatedAt: "2023-07-11T11:27:04.9+07:00",
        auditee_checked_by: null,
        auditor_checked_by: "2297-1625",
        evaluasi_ke: null,
        is_late: null,
        log_persetujuan_action_plan: [
          {
            id: 63,
            from: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            to: {},
            action_plan_id: 23,
            status: "Auditor",
            role: "Maker",
            note: null,
            create_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            update_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:22:11.09+07:00",
            updatedAt: "2023-07-11T11:22:11.09+07:00",
          },
          {
            id: 66,
            from: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            to: {},
            action_plan_id: 23,
            status: "Auditor",
            role: "Checker",
            note: "sfsf",
            create_by: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            update_by: {
              pn: "2297-1625",
              nama: "Ignatia Gladys R. Tondang",
              jabatan: "Auditor",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:23:50.154+07:00",
            updatedAt: "2023-07-11T11:23:50.154+07:00",
          },
          {
            id: 69,
            from: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            to: {},
            action_plan_id: 23,
            status: "Auditor",
            role: "Signer",
            note: "sdfsdf",
            create_by: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            update_by: {
              pn: "1973-0878",
              nama: "Titis Agung Pramono",
              jabatan: "ICU Solo",
            },
            is_approved: true,
            createdAt: "2023-07-11T11:27:04.904+07:00",
            updatedAt: "2023-07-11T11:27:04.904+07:00",
          },
        ],
        history: [
          {
            downloaded_at: "2023-07-24T08:07:18.120Z",
            downloaded_by: {
              nama: "Bahrul Ulum",
              pn: "00071542",
            },
          },
          {
            downloaded_at: "2023-07-26T07:33:14.762Z",
            downloaded_by: {
              nama: "Bahrul Ulum",
              pn: "00071542",
            },
          },
        ],
      },
    ],
    reset_rpm: null,
    attendance_rpm: null,
    notulen_rpm: null,
    berita_acara_rpm: null,
    document_rpm: [
      {
        id: 21,
        project_rpm_id: 21,
        dokumen: "Surat Evaluasi",
        tanggal_document: "2023-07-11T11:27:25.975+07:00",
        evaluasi_ke: 1,
        nama_lampiran: "Surat Evaluasi",
        document_location:
          "http://172.18.241.228:41111/cdn?id=1325171af3d1e7dceed2d44e02db54c0.pdf@Attandance - Exit.pdf@RPM",
        createdAt: "2023-07-11T11:27:25.975+07:00",
        updatedAt: "2023-07-11T11:27:25.975+07:00",
        history: [
          {
            downloaded_at: "2023-07-21T04:01:46.854Z",
            downloaded_by: {
              nama: "Bahrul Ulum",
              pn: "00071542",
            },
          },
          {
            downloaded_at: "2023-07-24T07:54:00.121Z",
            downloaded_by: {
              nama: "Bahrul Ulum",
              pn: "00071542",
            },
          },
          {
            downloaded_at: "2023-08-10T04:31:26.114Z",
            downloaded_by: {
              nama: "Bahrul Ulum",
              pn: "00071542",
            },
          },
        ],
      },
    ],
  },
  {
    project_rpm_id: 7,
    rpm: {
      id: 7,
      project_id: 20230125,
      nama_project: "Test 7",
      num_project: "20230125",
      status_project: "Final",
      batas_waktu: "2023-03-20T13:08:58.697+07:00",
      tim_audit: [
        {
          title: "ma",
          pn: "1991-0585",
          nama: "Eko Setiawan",
          jabatan: "Auditor",
        },
        {
          title: "kta",
          pn: "2297-1931",
          nama: "Annisa Vitasari",
          jabatan: "Auditor",
        },
      ],
      pic_auditee: {
        name: "Riesa",
        pn: "3427197",
      },
      auditee_pn: ["3427197"],
      auditor_pn: ["2297-1931", "00071542", "1991-0585"],
      makers_auditee: null,
      checkers_auditee: null,
      signers_auditee: null,
      makers_auditor: [
        {
          pn: "2297-1931",
          nama: "Annisa Vitasari",
          jabatan: "Auditor",
          deskripsi_tugas: "Maker",
        },
      ],
      checkers_auditor: [
        {
          pn: "1991-0585",
          nama: "Eko Setiawan",
          jabatan: "Auditor",
          deskripsi_tugas: "Checker",
        },
      ],
      signers_auditor: [
        {
          pn: "00071542",
          nama: "Bahrul Ulum",
          jabatan: "Auditor",
          deskripsi_tugas: "Signer",
        },
      ],
      num_evaluasi: 1,
      create_by: {
        pn: "00071542",
        nama: "Bahrul Ulum",
        jabatan: "Pgs Kepala Desk Internal Audit",
      },
      update_by: {
        pn: "00071542",
        nama: "Bahrul Ulum",
        jabatan: "Pgs Kepala Desk Internal Audit",
      },
      createdAt: "2023-03-20T13:09:38.065+07:00",
      updatedAt: "2023-07-12T17:47:35.348+07:00",
      status_rpm: "Final",
      kai: {
        nama: "Bahrul Ulum",
        pn: "00071542",
      },
      uka_kode: "aikp1",
    },
    kkpt_rpm: [
      {
        kkpt_rpm_id: 7,
        id: 7,
        kkpt_id: 9,
        nama_kkpt: "Test 7",
        project_rpm_id: 7,
        batas_waktu: "2023-03-20T13:08:58.697+07:00",
        rekomendasi_existing: 1,
        action_plan_existing: 1,
        rekomendasi_terisi: 1,
        action_plan_terisi: 1,
        createdAt: "2023-03-20T13:09:38.07+07:00",
        updatedAt: "2023-03-20T13:12:07.73+07:00",
        kkpt_ewp: {
          kkpt: {
            id: 9,
            exemplar_no: 1,
            is_kkpt_merge: false,
            kkpt_merge_from: null,
            kkpt_merge_to: null,
            judul_kkpt: "Test 7",
            is_temuan_berulang: false,
            mtd_stc_risk_type_kode: "1",
            mtd_stc_risk_type_name: "Resiko Umum",
            audit_focus_kode: "fa1",
            audit_focus_name: "Focus Audit 1",
            products_kode: ["TRA0085"],
            kondisi:
              "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
            kpi: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
            kriteria:
              "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
            tanggapan_manajemen: null,
            is_na: false,
            is_fraud: false,
            is_na_desc: null,
            created_at: "2023-03-16T09:20:30.801Z",
            create_by: "2297-1931",
            updated_at: "2023-03-16T09:26:05.428Z",
            update_by: "1991-0585",
            kkpa_id: 12,
            status_persetujuan: "105",
            status_persetujuan_kkpt: {
              kode: "105",
              name: "Final",
              description: null,
              create_by: "00136165",
              update_by: "00136165",
              is_active: true,
              created_at: "2021-12-20T05:04:20.382Z",
              update_at: "2021-12-20T05:04:20.382Z",
            },
            kkpt_sample_list: [
              {
                id: 22,
                value: "PAT.pdf",
                tipe_sample: "file",
                objek_sample_id: "19",
                created_at: "2023-03-16T09:21:52.780Z",
                create_by: "2297-1931",
                updated_at: "2023-03-16T09:21:52.780Z",
                update_by: "2297-1931",
                kkpt_id: 9,
              },
            ],
            kkpt_control_list: [
              {
                id: 9,
                control_kode: "C1",
                created_at: "2023-03-16T09:22:00.262Z",
                create_by: "2297-1931",
                updated_at: "2023-03-16T09:22:00.262Z",
                update_by: "2297-1931",
                kkpt_id: 9,
              },
            ],
            kkpt_penyebab_list: [
              {
                id: 10,
                penyebab_kode: "01.05.01",
                penyebab_name: "Ketergantungan pada pekerja tertentu",
                desc: "Test 7",
                pn: [
                  {
                    key: 0,
                    pn: {
                      pernr: "1270782017",
                      sname: "Melati",
                    },
                    nama: "Melati",
                    jabatan: "KTA",
                    tempat: "Jakarta",
                    tglLahir: "1996-05-06",
                    jenisKelamin: "P",
                    jobGrade: "1",
                    personGrade: "1",
                    mke: "Test",
                    mkj: "Test",
                    statusPerkawinan: "Lajang",
                  },
                ],
                created_at: "2023-03-16T09:22:59.392Z",
                create_by: "2297-1931",
                updated_at: "2023-03-16T09:22:59.392Z",
                update_by: "2297-1931",
                kkpt_id: 9,
              },
            ],
            kkpt_impact: {
              id: 9,
              impact_kode: "SR",
              desc_impact: "Test 7",
              financial_impact_kode: "SR",
              financial_type_impact_kode: "mk1",
              total_kerugian: "1417374",
              gross: "758585",
              list_kerugian: [
                {
                  key: 1,
                  jumlah_kerugian: 658688,
                  jenis_kerugian: "Actual Loss",
                  keterangan: "Loss",
                },
                {
                  key: 2,
                  jumlah_kerugian: 758686,
                  jenis_kerugian: "Potensial Loss",
                  keterangan: "Loss",
                },
              ],
              nonfinancial_impact_kode: "SR",
              list_nonfinancial: [
                {
                  nonfinancial_type_impact_kode: "cd1",
                  mtd_stc_impact_kode: "SR",
                },
                {
                  nonfinancial_type_impact_kode: "cd2",
                  mtd_stc_impact_kode: "SR",
                },
                {
                  nonfinancial_type_impact_kode: "cd3",
                  mtd_stc_impact_kode: "SR",
                },
                {
                  nonfinancial_type_impact_kode: "cd4",
                  mtd_stc_impact_kode: "SR",
                },
                {
                  nonfinancial_type_impact_kode: "cd5",
                  mtd_stc_impact_kode: "SR",
                },
              ],
              created_at: "2023-03-16T09:20:30.805Z",
              create_by: "2297-1931",
              updated_at: "2023-03-16T09:24:27.948Z",
              update_by: "2297-1931",
              kkpt_id: 9,
            },
            kkpt_likelihood: {
              id: 9,
              jumlah_populasi: 2,
              jumlah_sample: 1,
              jumlah_sample_bermasalah: 1,
              likelihood_kode: "SR",
              created_at: "2023-03-16T09:20:30.810Z",
              create_by: "2297-1931",
              updated_at: "2023-03-16T09:20:30.810Z",
              update_by: "2297-1931",
              kkpt_id: 9,
            },
            kkpt_kategori: {
              id: 9,
              kategori_temuan_kode: "2",
              adj_impact_kode: "SR",
              adj_likelihood_kode: "SR",
              adj_kategori_temuan_kode: "2",
              adj_alasan: "Test 7",
              adj_by: "2297-1931",
              adj_at: "2023-03-16T09:24:45.264Z",
              created_at: "2023-03-16T09:20:30.810Z",
              create_by: "2297-1931",
              updated_at: "2023-03-16T09:24:45.264Z",
              update_by: "2297-1931",
              kkpt_id: 9,
            },
            kkpt_rekomendasi_list: [
              {
                id: 10,
                tipe_rekomendasi_kode: "3",
                tipe_rekomendasi_name: "tindakan",
                desc: "Test 7",
                ref_uker_tujuan_branch_kode: 18,
                ref_uker_tujuan_branch_name: "KC JAKARTA BARAT",
                ref_uker_tujuan_orgeh: 18,
                ref_uker_tujuan_orgeh_name: "KP WEST JAKARTA",
                created_at: "2023-03-16T09:25:17.372Z",
                create_by: "2297-1931",
                updated_at: "2023-03-16T09:25:17.372Z",
                update_by: "2297-1931",
                kkpt_id: 9,
                action_plans: [
                  {
                    id: 11,
                    desc: "Test 8=7",
                    rekomendasi_id: 10,
                    ref_auditee_branch_kode: 15,
                    ref_auditee_orgeh: 15,
                    batas_waktu: "2023-03-20T06:08:58.697Z",
                    pic: "2297-1931",
                  },
                ],
              },
            ],
          },
          mapa_uker_mcr: {
            ref_mcr_kode: "1.1.PPP.PPP1",
            ref_risk_issue_kode: "PPP1",
            ref_risk_issue_name: "Control Masalah",
          },
          mapa_uker: {
            ref_auditee_branch_kode: 18,
            ref_auditee_branch_name: "KC JAKARTA BARAT",
            ref_auditee_orgeh_kode: 18,
            ref_auditee_orgeh_name: "KP WEST JAKARTA",
            tipe_uker: "kc",
          },
          ewp: {
            audit_year: 2023,
            audit_type_kode: "SA",
            audit_type_name: "Spesial Audit",
          },
          sub_major_proses: {
            kode: "PPP",
            nama: "Pemeriksaan",
            mtd_major_proses_kode: "1.1",
            is_active: true,
            mtd_major_proses: {
              kode: "1.1",
              nama: "Pengujian",
              mtd_mega_proses_kode: "1",
              is_active: true,
            },
          },
        },
        evaluasi_ke: 1,
        log_persetujuan_kkpt: [
          {
            id: 4,
            kkpt_id: 7,
            nama_kkpt: "Test 5",
            project_rpm_id: 4,
            batas_waktu: "2023-03-20T12:43:10.578+07:00",
            rekomendasi_existing: 1,
            action_plan_existing: 1,
            rekomendasi_terisi: 1,
            action_plan_terisi: 1,
            createdAt: "2023-03-20T12:45:01.163+07:00",
            updatedAt: "2023-03-20T12:50:07.491+07:00",
            kkpt_ewp: {
              kkpt: {
                id: 7,
                exemplar_no: 1,
                is_kkpt_merge: false,
                kkpt_merge_from: null,
                kkpt_merge_to: null,
                judul_kkpt: "Test 5",
                is_temuan_berulang: false,
                mtd_stc_risk_type_kode: "1",
                mtd_stc_risk_type_name: "Resiko Umum",
                audit_focus_kode: "fa2",
                audit_focus_name: "Focus Audit 2",
                products_kode: ["KUP0048"],
                kondisi:
                  "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
                kpi: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                kriteria:
                  "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
                tanggapan_manajemen: null,
                is_na: false,
                is_fraud: false,
                is_na_desc: null,
                created_at: "2023-03-16T08:31:20.921Z",
                create_by: "2297-1931",
                updated_at: "2023-03-16T08:36:18.065Z",
                update_by: "1991-0585",
                kkpa_id: 10,
                status_persetujuan: "105",
                status_persetujuan_kkpt: {
                  kode: "105",
                  name: "Final",
                  description: null,
                  create_by: "00136165",
                  update_by: "00136165",
                  is_active: true,
                  created_at: "2021-12-20T05:04:20.382Z",
                  update_at: "2021-12-20T05:04:20.382Z",
                },
                kkpt_sample_list: [
                  {
                    id: 20,
                    value: "PAT.pdf",
                    tipe_sample: "file",
                    objek_sample_id: "17",
                    created_at: "2023-03-16T08:32:28.541Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-16T08:32:28.541Z",
                    update_by: "2297-1931",
                    kkpt_id: 7,
                  },
                ],
                kkpt_control_list: [
                  {
                    id: 7,
                    control_kode: "C1",
                    created_at: "2023-03-16T08:32:35.983Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-16T08:32:35.983Z",
                    update_by: "2297-1931",
                    kkpt_id: 7,
                  },
                ],
                kkpt_penyebab_list: [
                  {
                    id: 8,
                    penyebab_kode: "03.03.02",
                    penyebab_name: "hacking",
                    desc: "Test 5 ",
                    pn: [
                      {
                        key: 0,
                        pn: {
                          pernr: "3037096",
                          sname: "Riesa",
                        },
                        nama: "Riesa",
                        jabatan: "KTA",
                        tempat: "Jakarta",
                        tglLahir: "1999-02-08",
                        jenisKelamin: "L",
                        jobGrade: "1",
                        personGrade: "1",
                        mke: "Test",
                        mkj: "Test",
                        statusPerkawinan: "Lajang",
                      },
                    ],
                    created_at: "2023-03-16T08:33:16.720Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-16T08:33:16.720Z",
                    update_by: "2297-1931",
                    kkpt_id: 7,
                  },
                ],
                kkpt_impact: {
                  id: 7,
                  impact_kode: "SR",
                  desc_impact: "Test 5",
                  financial_impact_kode: "SR",
                  financial_type_impact_kode: "mk1",
                  total_kerugian: "4759390",
                  gross: "2784921",
                  list_kerugian: [
                    {
                      key: 1,
                      jumlah_kerugian: 4759390,
                      jenis_kerugian: "Potensial Loss",
                      keterangan: "Test 5",
                    },
                  ],
                  nonfinancial_impact_kode: "SR",
                  list_nonfinancial: [
                    {
                      nonfinancial_type_impact_kode: "cd1",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd2",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd3",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd4",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd5",
                      mtd_stc_impact_kode: "SR",
                    },
                  ],
                  created_at: "2023-03-16T08:31:20.926Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-16T08:33:52.403Z",
                  update_by: "2297-1931",
                  kkpt_id: 7,
                },
                kkpt_likelihood: {
                  id: 7,
                  jumlah_populasi: 2,
                  jumlah_sample: 1,
                  jumlah_sample_bermasalah: 1,
                  likelihood_kode: "SR",
                  created_at: "2023-03-16T08:31:20.932Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-16T08:31:20.932Z",
                  update_by: "2297-1931",
                  kkpt_id: 7,
                },
                kkpt_kategori: {
                  id: 7,
                  kategori_temuan_kode: "2",
                  adj_impact_kode: "SR",
                  adj_likelihood_kode: "SR",
                  adj_kategori_temuan_kode: "2",
                  adj_alasan: "Test 5",
                  adj_by: "2297-1931",
                  adj_at: "2023-03-16T08:34:42.708Z",
                  created_at: "2023-03-16T08:31:20.932Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-16T08:34:42.708Z",
                  update_by: "2297-1931",
                  kkpt_id: 7,
                },
                kkpt_rekomendasi_list: [
                  {
                    id: 8,
                    tipe_rekomendasi_kode: "2",
                    tipe_rekomendasi_name: "corrective",
                    desc: "Test 5",
                    ref_uker_tujuan_branch_kode: 16,
                    ref_uker_tujuan_branch_name: "JAKARTA HO1",
                    ref_uker_tujuan_orgeh: 16,
                    ref_uker_tujuan_orgeh_name: "JAKARTA HO1",
                    created_at: "2023-03-16T08:35:16.574Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-16T08:35:16.574Z",
                    update_by: "2297-1931",
                    kkpt_id: 7,
                    action_plans: [
                      {
                        id: 8,
                        desc: "Test 5",
                        rekomendasi_id: 8,
                        ref_auditee_branch_kode: 12,
                        ref_auditee_orgeh: 12,
                        batas_waktu: "2023-03-20T05:43:10.578Z",
                        pic: "2297-1931",
                      },
                    ],
                  },
                ],
              },
              mapa_uker_mcr: {
                ref_mcr_kode: "1.1.PPP.PPP1",
                ref_risk_issue_kode: "PPP1",
                ref_risk_issue_name: "Control Masalah",
              },
              mapa_uker: {
                ref_auditee_branch_kode: 16,
                ref_auditee_branch_name: "JAKARTA HO1",
                ref_auditee_orgeh_kode: 16,
                ref_auditee_orgeh_name: "JAKARTA HO1",
                tipe_uker: "kc",
              },
              ewp: {
                audit_year: 2023,
                audit_type_kode: "TMT",
                audit_type_name: "Tematik",
              },
              sub_major_proses: {
                kode: "PPP",
                nama: "Pemeriksaan",
                mtd_major_proses_kode: "1.1",
                is_active: true,
                mtd_major_proses: {
                  kode: "1.1",
                  nama: "Pengujian",
                  mtd_mega_proses_kode: "1",
                  is_active: true,
                },
              },
            },
            evaluasi_ke: 1,
          },
        ],
      },
    ],
    action_plan_rpm: [
      {
        rpm_action_plan_id: 7,
        id: 7,
        project_rpm_id: 7,
        kkpt_id: 9,
        rekomendasi_kkpt: {
          prev_id: 10,
          id: 7,
          nama: "tindakan",
          description: "Test 7",
          ref_uker_tujuan_branch_kode: 18,
          ref_uker_tujuan_branch_name: "KC JAKARTA BARAT",
          ref_uker_tujuan_orgeh: 18,
          ref_uker_tujuan_orgeh_name: "KP WEST JAKARTA",
        },
        action_plan_kkpt: {
          prev_id: 11,
          id: 7,
          name: "Test 8=7",
          description: "Test 8=7",
        },
        batas_waktu: "2023-03-20T13:08:58.697+07:00",
        hasil_evaluasi: "Memadai",
        lampiran: [
          {
            key: "0.3513763704090065",
            attachment:
              "http://172.18.241.228:41111/cdn?id=443356f02dab4ba46c4867981e256345.pdf@PAT.pdf@RPM",
            deskripsi: "Test 7",
          },
        ],
        status_kode: "11",
        persetujuan_kode: "111",
        is_active: true,
        signed_by: ["00071542"],
        create_by: null,
        update_by: null,
        createdAt: "2023-03-20T13:09:38.073+07:00",
        updatedAt: "2023-03-20T13:12:07.74+07:00",
        auditee_checked_by: null,
        auditor_checked_by: "1991-0585",
        evaluasi_ke: null,
        is_late: null,
        log_persetujuan_action_plan: [
          {
            id: 19,
            from: {
              pn: "2297-1931",
              nama: "Annisa Vitasari",
              jabatan: "Auditor Sementara",
            },
            to: {},
            action_plan_id: 7,
            status: "Auditor",
            role: "Maker",
            note: null,
            create_by: {
              pn: "2297-1931",
              nama: "Annisa Vitasari",
              jabatan: "Auditor Sementara",
            },
            update_by: {
              pn: "2297-1931",
              nama: "Annisa Vitasari",
              jabatan: "Auditor Sementara",
            },
            is_approved: true,
            createdAt: "2023-03-20T13:11:24.199+07:00",
            updatedAt: "2023-03-20T13:11:24.199+07:00",
          },
          {
            id: 20,
            from: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            to: {},
            action_plan_id: 7,
            status: "Auditor",
            role: "Checker",
            note: "Ok",
            create_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            update_by: {
              pn: "1991-0585",
              nama: "Eko Setiawan",
              jabatan: "Junior Auditor",
            },
            is_approved: true,
            createdAt: "2023-03-20T13:11:45.774+07:00",
            updatedAt: "2023-03-20T13:11:45.774+07:00",
          },
          {
            id: 21,
            from: {
              pn: "00071542",
              nama: "Bahrul Ulum",
              jabatan: "Pgs Kepala Desk Internal Audit",
            },
            to: {},
            action_plan_id: 7,
            status: "Auditor",
            role: "Signer",
            note: "Ok",
            create_by: {
              pn: "00071542",
              nama: "Bahrul Ulum",
              jabatan: "Pgs Kepala Desk Internal Audit",
            },
            update_by: {
              pn: "00071542",
              nama: "Bahrul Ulum",
              jabatan: "Pgs Kepala Desk Internal Audit",
            },
            is_approved: true,
            createdAt: "2023-03-20T13:12:07.745+07:00",
            updatedAt: "2023-03-20T13:12:07.745+07:00",
          },
        ],
      },
    ],
    reset_rpm: null,
    attendance_rpm: null,
    notulen_rpm: null,
    berita_acara_rpm: null,
    document_rpm: [
      {
        id: 7,
        project_rpm_id: 7,
        dokumen: "Surat Evaluasi",
        tanggal_document: "2023-03-20T13:12:32.233+07:00",
        evaluasi_ke: 1,
        nama_lampiran: "Surat Evaluasi",
        document_location:
          "http://172.18.241.228:41111/cdn?id=97bb79bd99bcd4383edb31128474391a.pdf@PAT.pdf@RPM",
        createdAt: "2023-03-20T13:12:32.233+07:00",
        updatedAt: "2023-03-20T13:12:32.233+07:00",
      },
      {
        id: 22,
        project_rpm_id: 7,
        dokumen: "Surat Evaluasi",
        tanggal_document: "2023-07-12T17:47:35.355+07:00",
        evaluasi_ke: 1,
        nama_lampiran: "Surat Evaluasi",
        document_location:
          "http://172.18.241.228:41111/cdn?id=02f1d94ed50fe95a16d0849a0efa1f75.txt@final amt.txt@RPM",
        createdAt: "2023-07-12T17:47:35.355+07:00",
        updatedAt: "2023-07-12T17:47:35.355+07:00",
      },
    ],
  },
  {
    project_rpm_id: 22,
    rpm: {
      id: 22,
      project_id: 20240004,
      nama_project: "Audit UAT 2607",
      num_project: "20240004",
      status_project: "Final",
      batas_waktu: "2024-07-31T13:30:05.866+07:00",
      tim_audit: [
        {
          title: "ma",
          pn: "00071542",
          nama: "Bahrul Ulum",
          jabatan: "Auditor",
        },
        {
          title: "kta",
          pn: "1984-0704",
          nama: "Gamma Nur Akbar",
          jabatan: "Auditor",
        },
        {
          title: "ata",
          pn: "2293-1860",
          nama: "Agustinus Buulolo",
          jabatan: "Auditor",
        },
      ],
      pic_auditee: {
        name: "Mochamad Irfan",
        pn: "71157",
      },
      auditee_pn: ["71157"],
      auditor_pn: ["1984-0704", "00071542", "2293-1860"],
      makers_auditee: null,
      checkers_auditee: null,
      signers_auditee: null,
      makers_auditor: [
        {
          pn: "1984-0704",
          nama: "Gamma Nur Akbar",
          jabatan: "Auditor",
          deskripsi_tugas: "maker",
        },
      ],
      checkers_auditor: [
        {
          pn: "2293-1860",
          nama: "Agustinus Buulolo",
          jabatan: "Auditor",
          deskripsi_tugas: "checker",
        },
      ],
      signers_auditor: [
        {
          pn: "00071542",
          nama: "Bahrul Ulum",
          jabatan: "Auditor",
          deskripsi_tugas: "signer",
        },
      ],
      num_evaluasi: 1,
      create_by: {
        pn: "1984-0704",
        nama: "Gamma Nur Akbar",
        jabatan: "ICU Bekasi",
      },
      update_by: {
        pn: "1984-0704",
        nama: "Gamma Nur Akbar",
        jabatan: "ICU Bekasi",
      },
      createdAt: "2023-07-26T13:40:16.848+07:00",
      updatedAt: "2023-07-26T13:52:45.177+07:00",
      status_rpm: "Final",
      kai: {
        nama: "Bahrul Ulum",
        pn: "00071542",
      },
      uka_kode: "kns3",
    },
    kkpt_rpm: [
      {
        kkpt_rpm_id: 22,
        id: 22,
        kkpt_id: 34,
        nama_kkpt: "PDP2 - Breakdown RKAP (RKA/RKF) terlambat BRISMA",
        project_rpm_id: 22,
        batas_waktu: "2024-07-31T13:30:05.866+07:00",
        rekomendasi_existing: 1,
        action_plan_existing: 1,
        rekomendasi_terisi: 1,
        action_plan_terisi: 1,
        createdAt: "2023-07-26T13:40:16.853+07:00",
        updatedAt: "2023-07-26T13:51:26.563+07:00",
        kkpt_ewp: {
          kkpt: {
            id: 34,
            exemplar_no: 1,
            is_kkpt_merge: false,
            kkpt_merge_from: null,
            kkpt_merge_to: null,
            judul_kkpt: "PDP2 - Breakdown RKAP (RKA/RKF) terlambat BRISMA",
            is_temuan_berulang: false,
            mtd_stc_risk_type_kode: "7",
            mtd_stc_risk_type_name: "Risiko Kepatuhan",
            audit_focus_kode: "fa2",
            audit_focus_name: "Focus Audit 2",
            products_kode: ["AKU0006"],
            kondisi: "<p>UAT BRISMA Anak Perusahaan 2.1 2607</p>",
            kpi: "UAT BRISMA Anak Perusahaan 2.1 2607",
            kriteria: "<p>Test UAT 2607 BRISMA ANAK PERUSAHAAN Edit</p>",
            tanggapan_manajemen: "Tanggapan UAT",
            is_na: false,
            is_fraud: false,
            is_na_desc: null,
            created_at: "2023-07-26T04:50:49.746Z",
            create_by: "1984-0704",
            updated_at: "2023-07-26T06:29:35.984Z",
            update_by: "1984-0704",
            kkpa_id: 39,
            status_persetujuan: "105",
            status_persetujuan_kkpt: {
              kode: "105",
              name: "Final",
              description: null,
              create_by: "00136165",
              update_by: "00136165",
              is_active: true,
              created_at: "2021-12-20T05:04:20.382Z",
              update_at: "2021-12-20T05:04:20.382Z",
            },
            kkpt_sample_list: [
              {
                id: 64,
                value: "Catatan.txt",
                tipe_sample: "file",
                objek_sample_id: "34",
                created_at: "2023-07-26T06:18:35.519Z",
                create_by: "1984-0704",
                updated_at: "2023-07-26T06:18:35.519Z",
                update_by: "1984-0704",
                kkpt_id: 34,
              },
            ],
            kkpt_control_list: [
              {
                id: 44,
                control_kode: "C155",
                created_at: "2023-07-26T06:18:59.386Z",
                create_by: "1984-0704",
                updated_at: "2023-07-26T06:18:59.386Z",
                update_by: "1984-0704",
                kkpt_id: 34,
              },
            ],
            kkpt_penyebab_list: [
              {
                id: 37,
                penyebab_kode: "02.02.02",
                penyebab_name: "Kurangnya sosialisasi Produk",
                desc: "Penyebab oleh pn",
                pn: [],
                created_at: "2023-07-26T06:20:02.638Z",
                create_by: "1984-0704",
                updated_at: "2023-07-26T06:20:02.638Z",
                update_by: "1984-0704",
                kkpt_id: 34,
              },
            ],
            kkpt_impact: {
              id: 34,
              impact_kode: "ST",
              desc_impact: "kesimpulan",
              financial_impact_kode: "ST",
              financial_type_impact_kode: "mk0",
              total_kerugian: "250000",
              gross: "15000000",
              list_kerugian: [
                {
                  key: 1,
                  jumlah_kerugian: 250000,
                  jenis_kerugian: "Actual Loss",
                  keterangan: "Barang",
                },
              ],
              nonfinancial_impact_kode: "T",
              list_nonfinancial: [
                {
                  nonfinancial_type_impact_kode: "cd1",
                  mtd_stc_impact_kode: "R",
                },
                {
                  nonfinancial_type_impact_kode: "cd2",
                  mtd_stc_impact_kode: "SD",
                },
                {
                  nonfinancial_type_impact_kode: "cd3",
                  mtd_stc_impact_kode: "T",
                },
                {
                  nonfinancial_type_impact_kode: "cd4",
                  mtd_stc_impact_kode: "R",
                },
                {
                  nonfinancial_type_impact_kode: "cd5",
                  mtd_stc_impact_kode: "R",
                },
              ],
              created_at: "2023-07-26T04:50:49.749Z",
              create_by: "1984-0704",
              updated_at: "2023-07-26T06:23:07.542Z",
              update_by: "1984-0704",
              kkpt_id: 34,
            },
            kkpt_likelihood: {
              id: 34,
              jumlah_populasi: 1,
              jumlah_sample: 1,
              jumlah_sample_bermasalah: 1,
              likelihood_kode: "SR",
              created_at: "2023-07-26T04:50:49.754Z",
              create_by: "1984-0704",
              updated_at: "2023-07-26T04:50:49.754Z",
              update_by: "1984-0704",
              kkpt_id: 34,
            },
            kkpt_kategori: {
              id: 34,
              kategori_temuan_kode: "3",
              adj_impact_kode: null,
              adj_likelihood_kode: null,
              adj_kategori_temuan_kode: null,
              adj_alasan: null,
              adj_by: null,
              adj_at: null,
              created_at: "2023-07-26T04:50:49.754Z",
              create_by: "1984-0704",
              updated_at: "2023-07-26T06:23:07.548Z",
              update_by: "1984-0704",
              kkpt_id: 34,
            },
            kkpt_rekomendasi_list: [
              {
                id: 45,
                tipe_rekomendasi_kode: "2",
                tipe_rekomendasi_name: "corrective",
                desc: "Rekomendasi",
                ref_uker_tujuan_branch_kode: 19,
                ref_uker_tujuan_branch_name: "KC BEKASI",
                ref_uker_tujuan_orgeh: 19,
                ref_uker_tujuan_orgeh_name: "KC BEKASI",
                created_at: "2023-07-26T06:24:22.324Z",
                create_by: "1984-0704",
                updated_at: "2023-07-26T06:24:22.324Z",
                update_by: "1984-0704",
                kkpt_id: 34,
                action_plans: [
                  {
                    id: 31,
                    desc: "Action Plan UAT",
                    rekomendasi_id: 45,
                    ref_auditee_branch_kode: 19,
                    ref_auditee_orgeh: 19,
                    batas_waktu: "2024-07-31T06:30:05.866Z",
                    pic: "1984-0704",
                  },
                ],
              },
            ],
          },
          mapa_uker_mcr: {
            ref_mcr_kode: "1.1.PDP.PDP2",
            ref_risk_issue_kode: "PDP2",
            ref_risk_issue_name: "Breakdown RKAP (RKA/RKF) terlambat",
          },
          mapa_uker: {
            ref_auditee_branch_kode: 19,
            ref_auditee_branch_name: "KC BEKASI",
            ref_auditee_orgeh_kode: 19,
            ref_auditee_orgeh_name: "KC BEKASI",
            tipe_uker: "kc",
          },
          ewp: {
            audit_year: 2024,
            audit_type_kode: "REG",
            audit_type_name: "Regular Audit",
          },
          sub_major_proses: {
            kode: "PDP",
            nama: "Penyusunan & Distribusi Perencanaan Strategis",
            mtd_major_proses_kode: "1.1",
            is_active: true,
            mtd_major_proses: {
              kode: "1.1",
              nama: "Perencanaan Strategis",
              mtd_mega_proses_kode: "1",
              is_active: true,
            },
          },
        },
        evaluasi_ke: 1,
        log_persetujuan_kkpt: [
          {
            id: 20,
            kkpt_id: 22,
            nama_kkpt: "Test 21",
            project_rpm_id: 20,
            batas_waktu: "2023-03-20T14:27:12.945+07:00",
            rekomendasi_existing: 1,
            action_plan_existing: 1,
            rekomendasi_terisi: 1,
            action_plan_terisi: 1,
            createdAt: "2023-03-20T14:33:05.015+07:00",
            updatedAt: "2023-03-20T14:36:51.604+07:00",
            kkpt_ewp: {
              kkpt: {
                id: 22,
                exemplar_no: 1,
                is_kkpt_merge: false,
                kkpt_merge_from: null,
                kkpt_merge_to: null,
                judul_kkpt: "Test 21",
                is_temuan_berulang: true,
                mtd_stc_risk_type_kode: "1",
                mtd_stc_risk_type_name: "Resiko Umum",
                audit_focus_kode: "fa2",
                audit_focus_name: "Focus Audit 2",
                products_kode: ["KKB0037"],
                kondisi:
                  "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
                kpi: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                kriteria:
                  "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>",
                tanggapan_manajemen: null,
                is_na: false,
                is_fraud: false,
                is_na_desc: null,
                created_at: "2023-03-20T07:19:58.661Z",
                create_by: "2297-1931",
                updated_at: "2023-03-20T07:23:54.949Z",
                update_by: "1991-0585",
                kkpa_id: 26,
                status_persetujuan: "105",
                status_persetujuan_kkpt: {
                  kode: "105",
                  name: "Final",
                  description: null,
                  create_by: "00136165",
                  update_by: "00136165",
                  is_active: true,
                  created_at: "2021-12-20T05:04:20.382Z",
                  update_at: "2021-12-20T05:04:20.382Z",
                },
                kkpt_sample_list: [
                  {
                    id: 35,
                    value: "PAT.pdf",
                    tipe_sample: "file",
                    objek_sample_id: "33",
                    created_at: "2023-03-20T07:21:08.492Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T07:21:08.492Z",
                    update_by: "2297-1931",
                    kkpt_id: 22,
                  },
                ],
                kkpt_control_list: [
                  {
                    id: 23,
                    control_kode: "C1",
                    created_at: "2023-03-20T07:21:14.626Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T07:21:14.626Z",
                    update_by: "2297-1931",
                    kkpt_id: 22,
                  },
                ],
                kkpt_penyebab_list: [
                  {
                    id: 24,
                    penyebab_kode: "01.01.03",
                    penyebab_name: "Frekuensi training tidak memadai",
                    desc: "Test 21",
                    pn: [
                      {
                        key: 0,
                        pn: {
                          pernr: "1991-0585",
                          sname: "Riesa",
                        },
                        nama: "Riesa",
                        jabatan: "KTA",
                        tempat: "Jakarta",
                        tglLahir: "1996-08-21",
                        jenisKelamin: "L",
                        jobGrade: "1",
                        personGrade: "2",
                        mke: "Test",
                        mkj: "Test",
                        statusPerkawinan: "Menikah",
                      },
                    ],
                    created_at: "2023-03-20T07:22:07.778Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T07:22:07.778Z",
                    update_by: "2297-1931",
                    kkpt_id: 22,
                  },
                ],
                kkpt_impact: {
                  id: 22,
                  impact_kode: "ST",
                  desc_impact: "Test 21",
                  financial_impact_kode: "ST",
                  financial_type_impact_kode: "mk0",
                  total_kerugian: "442422",
                  gross: "858585",
                  list_kerugian: [
                    {
                      key: 1,
                      jumlah_kerugian: 442422,
                      jenis_kerugian: "Potensial Loss",
                      keterangan: "Loss",
                    },
                  ],
                  nonfinancial_impact_kode: "SR",
                  list_nonfinancial: [
                    {
                      nonfinancial_type_impact_kode: "cd1",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd2",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd3",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd4",
                      mtd_stc_impact_kode: "SR",
                    },
                    {
                      nonfinancial_type_impact_kode: "cd5",
                      mtd_stc_impact_kode: "SR",
                    },
                  ],
                  created_at: "2023-03-20T07:19:58.665Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-20T07:22:35.975Z",
                  update_by: "2297-1931",
                  kkpt_id: 22,
                },
                kkpt_likelihood: {
                  id: 22,
                  jumlah_populasi: 2,
                  jumlah_sample: 1,
                  jumlah_sample_bermasalah: 1,
                  likelihood_kode: "SR",
                  created_at: "2023-03-20T07:19:58.670Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-20T07:19:58.670Z",
                  update_by: "2297-1931",
                  kkpt_id: 22,
                },
                kkpt_kategori: {
                  id: 22,
                  kategori_temuan_kode: "3",
                  adj_impact_kode: "ST",
                  adj_likelihood_kode: "SR",
                  adj_kategori_temuan_kode: "3",
                  adj_alasan: "Test 21",
                  adj_by: "2297-1931",
                  adj_at: "2023-03-20T07:22:46.148Z",
                  created_at: "2023-03-20T07:19:58.670Z",
                  create_by: "2297-1931",
                  updated_at: "2023-03-20T07:22:46.149Z",
                  update_by: "2297-1931",
                  kkpt_id: 22,
                },
                kkpt_rekomendasi_list: [
                  {
                    id: 23,
                    tipe_rekomendasi_kode: "2",
                    tipe_rekomendasi_name: "corrective",
                    desc: "Test 21",
                    ref_uker_tujuan_branch_kode: 21,
                    ref_uker_tujuan_branch_name: "KC SURABAYA",
                    ref_uker_tujuan_orgeh: 21,
                    ref_uker_tujuan_orgeh_name: "KC SURABAYA",
                    created_at: "2023-03-20T07:23:06.575Z",
                    create_by: "2297-1931",
                    updated_at: "2023-03-20T07:23:06.575Z",
                    update_by: "2297-1931",
                    kkpt_id: 22,
                    action_plans: [
                      {
                        id: 24,
                        desc: "Test 21",
                        rekomendasi_id: 23,
                        ref_auditee_branch_kode: 21,
                        ref_auditee_orgeh: 21,
                        batas_waktu: "2023-03-20T07:27:12.945Z",
                        pic: "2297-1931",
                      },
                    ],
                  },
                ],
              },
              mapa_uker_mcr: {
                ref_mcr_kode: "1.1.PPP.PPP1",
                ref_risk_issue_kode: "PPP1",
                ref_risk_issue_name: "Control Masalah",
              },
              mapa_uker: {
                ref_auditee_branch_kode: 21,
                ref_auditee_branch_name: "KC SURABAYA",
                ref_auditee_orgeh_kode: 21,
                ref_auditee_orgeh_name: "KC SURABAYA",
                tipe_uker: "kc",
              },
              ewp: {
                audit_year: 2023,
                audit_type_kode: "SA",
                audit_type_name: "Spesial Audit",
              },
              sub_major_proses: {
                kode: "PPP",
                nama: "Pemeriksaan",
                mtd_major_proses_kode: "1.1",
                is_active: true,
                mtd_major_proses: {
                  kode: "1.1",
                  nama: "Pengujian",
                  mtd_mega_proses_kode: "1",
                  is_active: true,
                },
              },
            },
            evaluasi_ke: 1,
          },
        ],
      },
    ],
    action_plan_rpm: [
      {
        rpm_action_plan_id: 24,
        id: 24,
        project_rpm_id: 22,
        kkpt_id: 34,
        rekomendasi_kkpt: {
          prev_id: 45,
          id: 24,
          nama: "corrective",
          description: "Rekomendasi",
          ref_uker_tujuan_branch_kode: 19,
          ref_uker_tujuan_branch_name: "KC BEKASI",
          ref_uker_tujuan_orgeh: 19,
          ref_uker_tujuan_orgeh_name: "KC BEKASI",
        },
        action_plan_kkpt: {
          prev_id: 31,
          id: 24,
          name: "Action Plan UAT",
          description: "Action Plan UAT",
        },
        batas_waktu: "2024-07-31T13:30:05.866+07:00",
        hasil_evaluasi: "Memadai",
        lampiran: [
          {
            key: "0.6871235817167498",
            attachment:
              "http://172.18.241.228:41111/cdn?id=b038577bf8cd463eacaced6b1b33e702.txt@Catatan.txt@RPM",
            deskripsi: "UAT",
          },
        ],
        status_kode: "11",
        persetujuan_kode: "111",
        is_active: true,
        signed_by: ["00071542"],
        create_by: null,
        update_by: null,
        createdAt: "2023-07-26T13:40:16.857+07:00",
        updatedAt: "2023-07-26T13:51:26.579+07:00",
        auditee_checked_by: null,
        auditor_checked_by: "2293-1860",
        evaluasi_ke: null,
        is_late: null,
        log_persetujuan_action_plan: [
          {
            id: 70,
            from: {
              pn: "1984-0704",
              nama: "Gamma Nur Akbar",
              jabatan: "ICU Bekasi",
            },
            to: {},
            action_plan_id: 24,
            status: "Auditor",
            role: "Maker",
            note: null,
            create_by: {
              pn: "1984-0704",
              nama: "Gamma Nur Akbar",
              jabatan: "ICU Bekasi",
            },
            update_by: {
              pn: "1984-0704",
              nama: "Gamma Nur Akbar",
              jabatan: "ICU Bekasi",
            },
            is_approved: true,
            createdAt: "2023-07-26T13:50:05.012+07:00",
            updatedAt: "2023-07-26T13:50:05.012+07:00",
          },
          {
            id: 71,
            from: {
              pn: "2293-1860",
              nama: "Agustinus Buulolo",
              jabatan: "Auditor",
            },
            to: {},
            action_plan_id: 24,
            status: "Auditor",
            role: "Checker",
            note: "ok, approve",
            create_by: {
              pn: "2293-1860",
              nama: "Agustinus Buulolo",
              jabatan: "Auditor",
            },
            update_by: {
              pn: "2293-1860",
              nama: "Agustinus Buulolo",
              jabatan: "Auditor",
            },
            is_approved: true,
            createdAt: "2023-07-26T13:50:52.256+07:00",
            updatedAt: "2023-07-26T13:50:52.256+07:00",
          },
          {
            id: 72,
            from: {
              pn: "00071542",
              nama: "Bahrul Ulum",
              jabatan: "Pgs Kepala Desk Internal Audit",
            },
            to: {},
            action_plan_id: 24,
            status: "Auditor",
            role: "Signer",
            note: "ok, approve",
            create_by: {
              pn: "00071542",
              nama: "Bahrul Ulum",
              jabatan: "Pgs Kepala Desk Internal Audit",
            },
            update_by: {
              pn: "00071542",
              nama: "Bahrul Ulum",
              jabatan: "Pgs Kepala Desk Internal Audit",
            },
            is_approved: true,
            createdAt: "2023-07-26T13:51:26.583+07:00",
            updatedAt: "2023-07-26T13:51:26.583+07:00",
          },
        ],
        history: [
          {
            downloaded_at: "2023-07-26T07:32:26.991Z",
            downloaded_by: {
              nama: "Bahrul Ulum",
              pn: "00071542",
            },
          },
        ],
      },
    ],
    reset_rpm: null,
    attendance_rpm: null,
    notulen_rpm: null,
    berita_acara_rpm: null,
    document_rpm: [
      {
        id: 23,
        project_rpm_id: 22,
        dokumen: "Surat Evaluasi",
        tanggal_document: "2023-07-26T13:52:45.184+07:00",
        evaluasi_ke: 1,
        nama_lampiran: "Surat Evaluasi",
        document_location:
          "http://172.18.241.228:41111/cdn?id=ae4d31905a99859e24d191658f1d4aa8.txt@Catatan.txt@RPM",
        createdAt: "2023-07-26T13:52:45.184+07:00",
        updatedAt: "2023-07-26T13:52:45.184+07:00",
        history: [
          {
            downloaded_at: "2023-07-26T07:32:28.381Z",
            downloaded_by: {
              nama: "Bahrul Ulum",
              pn: "00071542",
            },
          },
        ],
      },
    ],
  },
];
const index = ({ data = rpmData }) => {
  // const [showFilter, setShowFilter] = useState(false);
  const breadcrumbs = [
    { name: "Menu", path: "/dashboard" },
    { name: "Catalogue", path: "/catalogue" },
    { name: "R.P.M", path: "/catalogue/rpm" },
  ];
  const [catRpm, setCatRpm] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  useEffect(() => {
    const mappingCatRpm = data?.map((v, key) => {
      return {
        No: key + 1,
        "Project ID": v?.rpm.project_id,
        "Nama Project": v?.rpm.nama_project,
        "Jenis Audit": "SPESIAL",
        "Periode Audit": "Triwulan " + "I" + " - " + 2023,
        "Tujuan Audit": "DIVISI TEKNOLOGI INFORMASI",
        "Tim Audit": v?.rpm.tim_audit.map((tim, key) => {
          return <p key={key}>{tim.pn + " - " + tim.nama}</p>;
        }),
        Auditee: v?.rpm.pic_auditee.name,
        Aksi: (
          <div className="rounded-full overflow-hidden border-2 border-atlasian-blue-light w-7 h-7 pt-0.5 mx-auto active:bg-slate-100">
            <Link href={"/catalogue/rpm/" + v.rpm.project_id} prefetch={true}>
              <Button
                shouldFitContainer
                iconBefore={
                  <IconArrowRight primaryColor="#0051CB" size="medium" />
                }
                className="bottom-1.5"
              />
            </Link>
          </div>
        ),
      };
    });
    setCatRpm(mappingCatRpm);
  }, []);
  return (
    <MainLayout>
      <div className="px-5">
        {/* Start Breadcrumbs */}
        <Breadcrumbs data={breadcrumbs} />
        {/* End Breadcrumbs */}
        <div className="flex justify-between items-center mb-6">
          <div className="flex-1">
            <div className="text-3xl font-bold">Catalogue R.P.M</div>
          </div>
        </div>
        {/* Start Filter */}
        {/* <div className="my-3 w-40">
          <Button
            appearance="primary"
            iconBefore={IconPlus}
            shouldFitContainer
            onClick={() => setShowFilter(!showFilter)}
          >
            Tampilkan Filter
          </Button>
        </div>
        {showFilter && (
          <div className="flex justify-between w-96">
            <Card>
              <div className="flex p-2">
                <div className="w-1/2 mr-1">
                  <Textfield
                    placeholder="ID Proyek"
                    elemAfterInput={
                      <button className="justify-center">
                        <IconClose size="large" />
                      </button>
                    }
                  />
                </div>
                <div className="w-1/2 ml-1">
                  <Select options={[]} placeholder="Status Dokumen" />
                </div>
              </div>
              <div className="flex p-2">
                <div className="w-1/2 mr-1">
                  <Textfield
                    placeholder="Nama Proyek"
                    elemAfterInput={
                      <button className="justify-center">
                        <IconClose size="large" />
                      </button>
                    }
                  />
                </div>
                <div className="w-1/2 ml-1">
                  <Select options={[]} placeholder="Status Persetujuan" />
                </div>
              </div>
            </Card>
          </div>
        )} */}
        {/* End Filter */}

        <div className="mt-5 mr-40">
          <Card>
            <div className="w-full h-full px-6">
              <div className="text-xl font-bold p-5">Pustaka Dokumen</div>
              <div className="max-h-[40rem] overflow-y-scroll px-2 mb-5">
                <TableField
                  headers={[
                    "No",
                    "Project ID",
                    "Nama Project",
                    "Jenis Audit",
                    "Periode Audit",
                    "Tujuan Audit",
                    "Tim Audit",
                    "Auditee",
                    "Aksi",
                  ]}
                  columnWidths={[
                    "5%",
                    "18%",
                    "15%",
                    "10%",
                    "12%",
                    "13%",
                    "12%",
                    "10%",
                    "5%",
                  ]}
                  items={catRpm}
                />
              </div>
              <div className="flex justify-center mt-5">
                <Pagination pages={1} setCurrentPage={setCurrentPage} />
              </div>
            </div>
          </Card>
        </div>
      </div>
    </MainLayout>
  );
};

export default index;
